# Generated by Django 5.2.15 on 2026-07-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shift_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='actual_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='actual_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='attendance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='completion_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('left_early', 'Left Early'), ('sick', 'Left Sick'), ('absent', 'Absent'), ('cancelled', 'Cancelled')], default='scheduled', max_length=30),
        ),
    ]
