# Generated by Django 5.2.15 on 2026-08-17 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_shift_actual_end_time_shift_actual_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='actual_end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='actual_start_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='attendance_notes',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='completion_status',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='shifts.department')),
            ],
            options={
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='shifts.unit'),
        ),
    ]
