# Generated by Django 5.2.15 on 2026-08-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_remove_shift_actual_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
