# Generated by Django 5.2.15 on 2026-08-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_ward_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('staff_nurse', 'Staff Nurse'), ('support_worker', 'Support Worker')], default='', max_length=30),
        ),
    ]
